version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - openwebui_data:/app/backend/data
    ports:
      - 8090:8080
    environment:
      - OLLAMA_BASE_URL=http://localhost:11434
      - WEBUI_SECRET_KEY=
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  openwebui_data: {}
